Repository Team-Beforeget/Beforeget-Android, pull requests merged in 2022-01, with the labels that each got.

#9 [Chore] Fix and Add Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/issue template.md
Labels: documentation, Android, 진수

#11 나의기록뷰 완성
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  .idea/sonarlint/issuestore/8/c/8c55c3ccc257e5907959013f99656e4c8ec3903e
  .idea/sonarlint/issuestore/e/4/e4e1ff17fa55edb12f3e2db8e3e3034e0ee27a25
  .idea/sonarlint/issuestore/index.pb
  app/src/main/AndroidManifest.xml
  app/src/main/java/beforeget/data/MyRecordAdapter.kt
  app/src/main/java/beforeget/data/MyRecordData.kt
  app/src/main/java/beforeget/feature/MainActivity.kt
  app/src/main/java/beforeget/feature/MyRecordActivity.kt
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/ic_beforeget_image.xml
  app/src/main/res/drawable/ic_filter_inactive_btn.xml
  app/src/main/res/drawable/ic_plus_btn.xml
  app/src/main/res/drawable/ic_serch_btn.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/activity_myrecod.xml
  app/src/main/res/layout/item_record.xml
Labels: ✏Android, 송현

#13 Feature/6 report labeling layout
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/sonarlint/issuestore/4/c/4c456519874116b46e77ca5a17c4eb320f30cafc
  .idea/sonarlint/issuestore/7/4/742746a5f024217bafe9631ee83df5b42ab43201
  .idea/sonarlint/issuestore/8/1/81b8e725ccff750656dd53ad51fe2e8e6e58580b
  .idea/sonarlint/issuestore/9/d/9d9d20011007edf00dd577cc1d446b95a206be53
  .idea/sonarlint/issuestore/e/1/e16ce5a8875c7951845d9083638f3eb3913b2698
  .idea/sonarlint/issuestore/f/0/f07866736216be0ee2aba49e392191aeae700a35
  .idea/sonarlint/issuestore/f/7/f7a6a0b565f9214a5b26c25a65532ca8d55d2889
  .idea/sonarlint/issuestore/f/b/fbe448ebfc3eb2d4e308f6b8b043666f5b57235e
  .idea/sonarlint/issuestore/index.pb
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/beforeget/feature/report/ReportActivity.kt
  app/src/main/java/beforeget/feature/report/ReportGraphFragment.kt
  app/src/main/java/beforeget/feature/report/ReportLabelingFragment.kt
  app/src/main/java/beforeget/feature/report/ReportOnepageFragment.kt
  app/src/main/java/beforeget/feature/report/ReportRankingFragment.kt
  app/src/main/java/beforeget/feature/report/ReportSentenceFragment.kt
  app/src/main/java/beforeget/feature/report/ReportViewPagerAdapter.kt
  app/src/main/res/drawable/ic_btn_back.xml
  app/src/main/res/drawable/ic_btn_download.xml
  app/src/main/res/drawable/ic_icn_star.xml
  app/src/main/res/drawable/ic_page1_active.xml
  app/src/main/res/drawable/ic_page1_inactive.xml
  app/src/main/res/drawable/ic_rectangle_report_label.xml
  app/src/main/res/drawable/rectangle_border_gray_18.xml
  app/src/main/res/drawable/tab_selector_report.xml
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/fragment_report_graph.xml
  app/src/main/res/layout/fragment_report_labeling.xml
  app/src/main/res/layout/fragment_report_onepage.xml
  app/src/main/res/layout/fragment_report_ranking.xml
  app/src/main/res/layout/fragment_report_sentence.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#18 Feature/14 report ranking layout
  app/src/main/res/drawable/ic_icn_star_green.xml
  app/src/main/res/drawable/rectangle_fill_black.xml
  app/src/main/res/layout/fragment_report_ranking.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#37 [Feat] Retrofit Enqueue 사용 부분 개선
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/java/before/forget/util/RetrofitCallbackUtil.kt
  app/src/test/java/before/forget/util/RequestInfoWrapperTest.kt
Labels: ✏Android, 🤨진수

#44 Feature/19 report labeling inflate
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/build.gradle
  app/src/main/java/before/forget/feature/report/ReportActivity.kt
  app/src/main/java/before/forget/feature/report/ReportLabelingFragment.kt
  app/src/main/java/before/forget/feature/report/ReportViewPagerAdapter.kt
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/fragment_report_labeling.xml
  app/src/main/res/layout/layout_report_datepicker_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#54 Feature/24 report sentence layout
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/feature/report/CardFlipBack.kt
  app/src/main/java/before/forget/feature/report/CardFlipFront.kt
  app/src/main/res/animator/cardflip_left_in.xml
  app/src/main/res/animator/cardflip_left_out.xml
  app/src/main/res/animator/cardflip_right_in.xml
  app/src/main/res/animator/cardflip_right_out.xml
  app/src/main/res/drawable/ic_icn_star.xml
  app/src/main/res/drawable/ic_img_sentence.xml
  app/src/main/res/drawable/ic_img_sentence_back.xml
  app/src/main/res/drawable/rectangle_border_green_3.xml
  app/src/main/res/layout/fragment_report_graph.xml
  app/src/main/res/layout/fragment_report_labeling.xml
  app/src/main/res/layout/fragment_report_ranking.xml
  app/src/main/res/layout/item_card_back.xml
  app/src/main/res/layout/item_card_front.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#57 55 report sentence inflate
  app/src/main/java/before/forget/feature/report/ReportSentenceFragment.kt
  app/src/main/res/layout/fragment_report_sentence.xml
Labels: 😳화진, ✏Android

#58 56 report onepage layout
  app/src/main/java/before/forget/feature/report/ReportOnepageFragment.kt
  app/src/main/res/layout/fragment_report_onepage.xml
Labels: 😳화진, ✏Android

#59 Feature/6 report labeling layout
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/feature/report/ReportActivity.kt
  app/src/main/res/drawable/ic_btn_share.xml
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/fragment_report_labeling.xml
Labels: 😳화진, ✏Android

#70 [FEAD] Report Labeling Remote
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/before/forget/data/remote/BeforegetClient.kt
  app/src/main/java/before/forget/data/remote/api/StatisticService.kt
  app/src/main/java/before/forget/data/remote/response/ReportLabelingData.kt
  app/src/main/java/before/forget/feature/report/ReportActivity.kt
  app/src/main/java/before/forget/feature/report/ReportLabelingFragment.kt
  app/src/main/res/layout/fragment_report_labeling.xml
Labels: 😳화진, ✏Android

#81 [FEAT] Report Graph Remote
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/data/remote/api/StatisticService.kt
  app/src/main/java/before/forget/data/remote/response/ResponseGraphData.kt
  app/src/main/java/before/forget/feature/report/ReportGraphFragment.kt
  app/src/main/java/before/forget/feature/report/ReportLabelingFragment.kt
  app/src/main/res/layout/fragment_report_graph.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#82 [FEAT] Report Ranking Remote
  app/src/main/java/before/forget/data/remote/api/StatisticService.kt
  app/src/main/java/before/forget/data/remote/response/ResponseRankingData.kt
  app/src/main/java/before/forget/feature/report/ReportRankingFragment.kt
  app/src/main/res/layout/fragment_report_ranking.xml
Labels: 😳화진, ✏Android

#91 [FEAT] Report Sentence Remote
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/data/remote/api/StatisticService.kt
  app/src/main/java/before/forget/data/remote/response/ReponseSentenceData.kt
  app/src/main/java/before/forget/feature/report/CardFlipBack.kt
  app/src/main/java/before/forget/feature/report/CardFlipFront.kt
  app/src/main/java/before/forget/feature/report/ReportSentenceFragment.kt
  app/src/main/res/layout/fragment_report_sentence.xml
Labels: 😳화진, ✏Android

#92 [FEAT] Report Onepage Remote
  app/src/main/java/before/forget/data/remote/api/StatisticService.kt
  app/src/main/java/before/forget/data/remote/response/ResponseOnepageData.kt
  app/src/main/java/before/forget/feature/report/ReportOnepageFragment.kt
  app/src/main/res/layout/fragment_report_onepage.xml
Labels: 😳화진, ✏Android

#94 Feature/6 report labeling layout
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/data/remote/response/ResponseOnepageData.kt
  app/src/main/res/layout/fragment_report_labeling.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#95 [BUG] Report Layout
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/feature/report/ReportGraphFragment.kt
  app/src/main/java/before/forget/feature/report/ReportOnepageFragment.kt
  app/src/main/res/layout/fragment_report_graph.xml
  app/src/main/res/layout/fragment_report_ranking.xml
  app/src/main/res/layout/fragment_report_sentence.xml
Labels: 😳화진, ✏Android

#96 [BUG] 디자인 요청 사항
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/feature/report/ReportGraphFragment.kt
  app/src/main/java/before/forget/feature/report/ReportOnepageFragment.kt
Labels: 😳화진, ✏Android

#99 [FEAT] Setting Layout
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/AndroidManifest.xml
  app/src/main/java/before/forget/feature/main/MainActivity.kt
  app/src/main/java/before/forget/feature/setting/SettingActivity.kt
  app/src/main/res/drawable/ic_btn_nameedit.xml
  app/src/main/res/drawable/ic_btn_next.xml
  app/src/main/res/drawable/ic_icn_about.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#102 Feature/98 myrecord dialog layout
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/feature/myrecord/detail/MyRecordDetailActivity.kt
  app/src/main/res/drawable/ic_img_delete.xml
  app/src/main/res/layout/dialog_record_detail_delete.xml
  app/src/main/res/values/strings.xml
Labels: 😳화진, ✏Android

#113 [FEAT]: Change Write Complete Activity Button Click Listener
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/feature/write/WriteCompleteActivity.kt
Labels: 😳화진, ✏Android

#114 Feature/104 write complete layout
  app/src/main/java/before/forget/feature/write/WriteCompleteActivity.kt
Labels: 😳화진, ✏Android

#117 [FEAT} WriteAcitivty Chip Button
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/before/forget/feature/write/WriteActivity.kt
  app/src/main/res/drawable/ic_btn_review_delete.xml
Labels: 😳화진, ✏Android
